cmake_minimum_required(VERSION 3.20)
project(ocex_modeling_benchmark LANGUAGES CXX)
find_package(OpenCASCADE 7.9.3 EXACT REQUIRED COMPONENTS FoundationClasses ModelingData ModelingAlgorithms)
add_executable(modeling modeling.cpp)
target_compile_features(modeling PRIVATE cxx_std_17)
target_include_directories(modeling SYSTEM PRIVATE "${OpenCASCADE_INCLUDE_DIR}")
target_link_directories(modeling PRIVATE "${OpenCASCADE_LIBRARY_DIR}")
target_link_libraries(modeling PRIVATE TKernel TKMath TKG2d TKG3d TKGeomBase TKBRep TKGeomAlgo TKTopAlgo TKPrim TKBO TKShHealing TKBool TKFillet)
target_compile_options(modeling PRIVATE -Wall -Wextra -Werror)
